config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    # omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  root to: "pages#home"
  get "dashboard", to: "pages#dashboard"

  get "settings", to: "pages#settings"

  get "projects/completed", to: "projects#index_complete", as: "completed_projects"
  get "calendar", to: "pages#calendar", as: "calendar"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources "projects" do
    get "active", to: "projects#set_active", as: "active"
    get "unmark", to: "projects#unmark_active", as: "unmark_active"
    get "complete", to: "projects#complete", as: "complete"
    get "incomplete", to: "projects#incomplete", as: "incomplete"

    resources "tasks", only: %i[new create update destroy]
  end

  get "tasks/:id/checkbox", to: "tasks#checkbox", as: "checkbox"

  resources "schedules", only: %i[index new show create edit update destroy]
  resources "notifications", only: %i[destroy]

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :user
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :set_schedule, only: %I[show destroy edit update]

  def index
    @schedules = Schedule.all
  end

  def new
    @schedule = Schedule.new
  end

  def show
  end

  def create
    unless current_user.schedule.nil?
      @old_schedule = current_user.schedule
      @old_schedule.destroy
    end
    @schedule = Schedule.new(schedule_params)
    @schedule.user = current_user
    if @schedule.save
      # set_notification
      redirect_to dashboard_path, notice: "schedule was successfully created!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    @schedule.update(update_schedule_params)

    if @schedule.save
      # set_notification
      respond_to do |format|
        format.html { redirect_to dashboard_path }
        format.text { render partial: "pages/schedule", locals: { user: current_user }, formats: [:html] }
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @schedule.destroy
    redirect_to schedules_path
  end

  private

  def set_schedule
    @schedule = Schedule.find(params[:id])
  end

  def schedule_params
    params.require(:schedule).permit(:start_time, :end_time, :lunch_break)
  end

  def update_schedule_params
    params.require(:schedule).permit(:start_time, :end_time, :lunch_break)
  end

  def set_notification
    NotificationJob.set(wait_until: (Time.now + 10.seconds)).perform_later(current_user)
  end
end

app/views/schedules/_edit_form.html.erb
<div class="d-none" >
  <% unless user.schedule.nil? %>
    <%= form_for(user.schedule, data: {start_target: "form"}, html:{id: "table"}) do |f| %>
      <h1>Edit a Schedule</h1>
      <%= f.label :start_time %>
      <%= f.time_field :start_time, placeholder: "Start Time", class:"fields-1 w-100" %>
      <br/>
      <%= f.label :lunch_break %>
      <%= f.time_field :lunch_break, placeholder: "Lunch Break", class:"fields-1 w-100" %>
      <br/>
      <%= f.label :end_time %>
      <%= f.time_field :end_time, placeholder: "End Time", class:"fields-1 w-100"%>
      <br/>
      <%= f.submit class:"button-1 border-0 w-100 d-flex justify-content-center" %>

    <% end %>
  <% end %>
</div>

app/views/schedules/_form.html.erb
  <div class="form-box-2 ">
    <%= form_for(schedule) do |f| %>
      <div class="create-schedule-card">
        <h1>Create Schedule</h1>
        <%= f.label :start_time %>
        <%= f.time_field :start_time, placeholder: "Start Time", class:"create-field w-100" %>
        <br/>
        <%= f.label :lunch_break %>
        <%= f.time_field :lunch_break, placeholder: "Lunch Break", class:"create-field w-100" %>
        <br/>
        <%= f.label :end_time %>
        <%= f.time_field :end_time, placeholder: "End Time", class:"create-field w-100" %>
        <br/>
        <br/>
        <%= f.submit class:"button-1 border-0 w-100 d-flex justify-content-center" %>
      </div>
    <% end %>
  </div>

app/views/schedules/edit.html.erb
<div class="card col-6 shadow-lg p-3 mb-5 bg-white rounded" style="width: 50rem; margin: auto; border-radius: 5px;">
  <div class="card-body ">
  <h1 class="text-center">Edit your Schedule</h1>
<%= render "edit_form", schedule: @schedule %>
  </div>
</div>

app/views/schedules/index.html.erb
<h1>All Schedules</h1>
    <%= link_to "Add Schedule", new_schedule_path, class:"button-1 gco -"%>

<ul class="mt-5">
  <% @schedules.each do |schedule| %>
    <li>
      <%= link_to schedule_path(schedule) do %>
        <%= schedule.start_time %> - <%= schedule.end_time %>
      <% end %>
      <%= link_to "Delete", schedule_path(schedule), method: :delete, data: { confirm: "Are you sure?" } %>
    </li>
  <% end %>
</ul>

app/views/schedules/new.html.erb
<div >
  <%= render "form", schedule: @schedule %>
</div>