config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    # omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  root to: "pages#home"
  get "dashboard", to: "pages#dashboard"

  get "settings", to: "pages#settings"

  get "projects/completed", to: "projects#index_complete", as: "completed_projects"
  get "calendar", to: "pages#calendar", as: "calendar"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources "projects" do
    get "active", to: "projects#set_active", as: "active"
    get "unmark", to: "projects#unmark_active", as: "unmark_active"
    get "complete", to: "projects#complete", as: "complete"
    get "incomplete", to: "projects#incomplete", as: "incomplete"

    resources "tasks", only: %i[new create update destroy]
  end

  get "tasks/:id/checkbox", to: "tasks#checkbox", as: "checkbox"

  resources "schedules", only: %i[index new show create edit update destroy]
  resources "notifications", only: %i[destroy]

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/shared/_footer.html.erb
<footer>
  <div class="footer fixed-bottom">
    <div class="footer-links">
      <a href="#"><i class="fab fa-github"></i></a>
      <a href="#"><i class="fab fa-instagram"></i></a>
      <a href="#"><i class="fab fa-facebook"></i></a>
      <a href="#"><i class="fab fa-twitter"></i></a>
      <a href="#"><i class="fab fa-linkedin"></i></a>
    </div>
    <div class="footer-copyright">
      2023 All Rights Reserved © WorkSmart.me <i class="fas fa-heart"></i>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<% if current_user == nil %>
  <div class="landing-page">
    <header>
      <div class="container">
        <div class="">
          <%= image_tag "Logo.png", class:"logo" %>
        </div>
        <ul class="links navbar-text">
          <li><%= link_to "Home", root_path, class:"navbar-text1"  %></li>
          <li><%= link_to "About us", root_path, class:"navbar-text1"  %></li>
          <li><%= link_to "Features", root_path, class:"navbar-text1"  %></li>
          <li><%= link_to "Log in", user_session_path, class:"nabar-button-login"  %></li>
          <li>
            <div class="container-button-3">
              <button class="button-3 ">
              <span><%= link_to "Register Now ", new_user_registration_path  %></span></button>
            </div>
          </li>
        </ul>
      </div>
    </header>
  </div>
<% else %>
  <div class="landing-page">
    <header class="d-flex my-auto justify-content-between">
      <div class=" d-flex my-auto menu">
        <i class="fa-solid fa-bars my-auto" data-action="click->sidebar#toggle"></i>
      </div>
      <div class="my-auto ps-5 ms-5 ">
        <%= image_tag 'Logo.png', class:"logo"  %>
      </div>
        <div class="container-button-3 button-space">
          <button class="button-3" data-action="click->start#updateSchedule">
          <span>Start Working!</span></button>
        </div>
    </header>
  </div>

<% end %>

app/views/shared/_notification.html.erb
<div class="card notification">
  <p>Test Notification</p>
  <%= link_to "Delete",
            notification_path(current_user.notification.id),
            data: {turbo_method: :delete, turbo_confirm: "Are you sure?"},
            class:"my-auto button-2"
%>
</div>

app/views/shared/_sidebar.html.erb
<div class="d-flex flex-column flex-shrink-0 p-3 bg-light d-none" id="sidebar" style="width: 280px;" data-sidebar-target="sidebar">
    <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-dark text-decoration-none">
      <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
      <%= image_tag "Logo2.png",class:"logo-2" %>
      <span class="logo-text">WorkSmart</span>
    </a>
    <hr>
    <ul class="nav nav-pills flex-column mb-auto text-start ">
      <%= link_to dashboard_path do %>
        <li class="nav-item nav-link link-dark sidebar-item home-text w-100 ">
        <%= image_tag "icon1.svg" %>
          <svg class="bi me-2 " width="16" height="16"><use xlink:href="#home"></use></svg>
           <b>Home</b>
        </li>
      <% end %>
      <%= link_to projects_path do %>
        <li class="nav-item nav-link link-dark sidebar-item home-text w-100">
        <%= image_tag "icon2.svg" %>
          <svg class="bi me-2" width="16" height="16"><use xlink:href="#home" ></use></svg>
          <b>All Projects</b>
        </li>
      <% end %>
      <%= link_to new_project_path do %>
        <li class="nav-item nav-link link-dark sidebar-item home-text w-100">
        <%= image_tag "icon3.svg" %>
          <svg class="bi me-2" width="16" height="16"><use xlink:href="#home"></use></svg>
            <b>Add Project</b>
        </li>
      <% end %>
      <%= link_to calendar_path do %>
        <li class="nav-item nav-link link-dark sidebar-item home-text w-100">
        <%= image_tag "icon8.svg" %>
          <svg class="bi me-2" width="16" height="16"><use xlink:href="#" ></use></svg>
          <b>Calendar</b>
        </li>
      <% end %>
      <%= link_to edit_user_registration_path do %>

        <li class="nav-item nav-link link-dark sidebar-item home-text w-100">
        <%= image_tag "icon6.png" %>
          <svg class="bi me-2" width="16" height="16"><use xlink:href="#" ></use></svg>
          <b>Setting</b>
        </li>
      <% end %>
      <%= link_to destroy_user_session_path, data: {turbo_method: :delete}, class:"link-dark sidebar-item" do  %>
        <li class="nav-item nav-link  link-dark sidebar-item home-text w-100 a ">
          <%= image_tag "icon5.svg" %>
          <svg class="bi me-2" width="16" height="16"><use xlink:href="#home"></use></svg>
           <b>Logout</b>
        </li>
      <% end %>
    </ul>
</div>