config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    # omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  root to: "pages#home"
  get "dashboard", to: "pages#dashboard"

  get "settings", to: "pages#settings"

  get "projects/completed", to: "projects#index_complete", as: "completed_projects"
  get "calendar", to: "pages#calendar", as: "calendar"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources "projects" do
    get "active", to: "projects#set_active", as: "active"
    get "unmark", to: "projects#unmark_active", as: "unmark_active"
    get "complete", to: "projects#complete", as: "complete"
    get "incomplete", to: "projects#incomplete", as: "incomplete"

    resources "tasks", only: %i[new create update destroy]
  end

  get "tasks/:id/checkbox", to: "tasks#checkbox", as: "checkbox"

  resources "schedules", only: %i[index new show create edit update destroy]
  resources "notifications", only: %i[destroy]

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/pages/_schedule.html.erb
<div data-start-target="change">
    <div>
      <%= render "schedules/edit_form", user: user %>
    </div>

    <div class= "" >
      <div class="m-3">
        <div class="new-box-3">
          <h2 class="text-2  box-project-3"><%= Date.today.strftime("%d-%m-%Y") %></h2>
        </div>
        <br/>

        <% if user.schedule == nil %>
          <p class="text-2 text-center">You don't have any schedule yet</p>
        <% else %>
          <% start_time = user.schedule.start_time %>
          <% lunch_break = user.schedule.lunch_break %>

          <% received_end_time = user.work_hours %>
          <% end_time_duration = received_end_time.hours %>
          <% end_time = start_time + end_time_duration %>

          <% mid_time1 = start_time + (lunch_break - start_time) / 2 %>
          <% mid_time2 = lunch_break + (end_time - lunch_break) / 2 %>
          <% mid_time3 = start_time + (end_time - start_time) / 2 %>
          <% mid_time4 = start_time + (mid_time3 - start_time) / 2 %>
          <% mid_time5 = mid_time3 + (end_time - mid_time3) / 2 %>

          <ul class="text-position-3">
            <li data-start-target="startTime" class="text-2" >Start Time: <b><%= start_time.strftime("%H:%M") %></b></li>
            <br/>
            <% if (start_time < lunch_break) && (lunch_break < end_time) %>
              <li data-start-target="firstBreak" class="text-2">Break: <%= mid_time1.strftime('%H:%M') %></li>
              <br/>
              <li class="text-2">Lunch Break: <b><%= lunch_break.strftime('%H:%M') %></b></li>
              <br/>
              <li class="text-2">Break: <%= mid_time2.strftime('%H:%M') %></li>
              <br/>
              <% else %>
              <li data-start-target="firstBreak" class="text-2">Break: <%= mid_time4.strftime('%H:%M') %></li>
              <br/>
              <li class="text-2">Break: <%= mid_time3.strftime('%H:%M') %></li>
              <br/>
              <li class="text-2">Break: <%= mid_time5.strftime('%H:%M') %></li>
              <br/>
            <% end %>
            <li class="text-2 pb-3">End Time: <b><%= end_time.strftime("%H:%M")  %></b></li>

          </ul>

        <% end %>


      </div>
    </div>
  </div>

app/views/pages/calendar.html.erb
<div class="scrollable-table ">

  <% if @projects.any? %>
    <div class="container mt-5 text-center ">
      <%= month_calendar(event: @projects) do |date| %>
        <div class="day">
          <%= date.day  %>
        </div>
        <% @projects.each do |project| %>
          <% if (project.start_date..project.dead_line).cover?(date)%>
            <div class="card-header">
              <div class="card-title">
                <% if project.completed == true %>
                  <li><%=  link_to project.name, project%></li>
                <% else %>
                  <li><%=  link_to project.name, project, class:"incomplete-text" %></li>
                <% end %>
              </div>
            </div>
          <% end %>
        <% end %>
      <% end %>
    </div>
  <% else %>
    <div class="calendar-page2">
      <p>No projects found for this period.</p>
      <%= link_to " Back to Calendar", calendar_path  %>
    </div>
  <% end %>

</div>

app/views/pages/dashboard.html.erb
<div class="page-grid" data-controller="schedule">

    <% if @user.projects == [] || @prioritised_projects == []%>
      <div class="priority-card">
        <p class= "text-2 text-center pt-5 " >You don't have any projects yet</p>
        <%= link_to new_project_path do %>
        <p class=" text-2 position3 w-25  button-5"><b>Add Project</b></p>
       <% end %>

    <% elsif @active_project == nil %>
      <%= link_to project_path(@prioritised_projects.first.id) do %>
        <div class="priority-card">
          <div class="new-box-1">
            <h2 class= "text-2 box-project">Priority Project</h2>
          </div>
          <div>
            <p class="text-5 pb-2 text-position-1"><%= @prioritised_projects.first.name %></p>
            <p class="text-4 pt-5 text-position-1"><%= @prioritised_project_percentage %>% completed</p>
            <div class="bar-size-position">
              <div class="progress" >
                <div class="progress-bar" role="progressbar" style="width: <%= @prioritised_project_percentage %>%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
              </div>
            </div>
          </div>
      <% end %>

    <% else %>
      <%= link_to project_path(@active_project.id) do %>
        <div class="priority-card">
          <div class="new-box-1">
            <h2 class= "text-2 box-project">Active Project</h2>
          </div>
          <div>
            <p class="text-5 pb-2 text-position-1"><%= @active_project.name %></p>
            <p class="text-4 pt-5 text-position-1"><%= @active_project_percentage%>% completed</p>
            <div class="bar-size-position">
              <div class="progress" >
                <div class="progress-bar" role="progressbar" style="width: <%= @active_project_percentage %>%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
              </div>
            </div>
          </div>
      <% end %>
    <% end %>
  </div>


  <div class= "view-card" >
    <div class="new-box-2">
      <h2 class="text-2 box-project-2 pt-4">View Projects</h2>
    </div>
    <div>
      <% if @unfinished_projects == nil %>
        <p class="text-2 text-center pt-5">You don't have any projects yet</p>
      <% else %>
      <ul>
      <div class="pt-3">
        <% @unfinished_projects.first(4).each do |project| %>
          <%= link_to project_path(project.id) do %>
            <li class="text-4 text-position-2"> <%= project.name %></li>
          <% end %>
        <% end %>
      <div>
      </ul>
      <% end %>
      <%= link_to projects_path do %>
        <div class="see-project">
          <p class= "text-3 pt-3 ">See all Projects</p>
          <%= image_tag 'Icons.svg' %>
        </div>
      <% end %>
    </div>
  </div>


  <%# --------- SCHEDULE ---------- %>
  <div class="schedule-card ">
    <%= render "pages/schedule", user: current_user %>
    <%= link_to "Create schedule", new_schedule_path, class:"create" %>
  </div>
</div>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
</head>

<body>

<div class="landing-page">
  <div class="content pt-5">
    <div class="container">
      <div class="info">
        <h1 class="text-2">Think Less, Live More</h1>
        <div>
          <h1 class= "Green-text work-smart">WorkSmart</h1>
        </div>
        <p class="dash-text4">Deliver your best work with work-smart.me</p>
        <%= link_to new_user_registration_path do %>
          <button class="register-button">Register Now!</button>
        <% end %>
      </div>
      <div class="image">
        <%= image_tag 'home.png' %>
      </div>
    </div>
  </div>
</div>
<section class="about" id="about">
  <div class="container">
    <div class="heading text-center">
        <h2 class="text-2">A platform built for a <span>new way of working</span></h2>
        <p class="dash-text4">Take control of your ideal workflow, your way<br>Manage your projects, view your workflow, plan your schedule, be healthy and efficient with your workflow.</p>
    </div>
  <div class="row">
    <div class="col-lg-6">
      <img src="https://img.freepik.com/free-photo/employee-sitting-with-hands-head-relax-after-finishing-job-desk-business-man-feeling-calm-peaceful-relaxing-office-after-working-project-planning-person-break_482257-34948.jpg?w=1380&t=st=1694074190~exp=1694074790~hmac=933f1def2b28e60514576a1c55a5f99ead07c18eabaa64ed815e4ee8561c08d3" alt="about" class="img-fluid" width="95%">
    </div>
  <div class="col-lg-6">
      <h3 class="text-2">Streamline your work for maximum productivity</h3>
      <p class="dash-text4">Centralize all your work, projects, and schedule into one efficient app. Keep track of your work progress and your hours spent on each project.</p>
  <div class="row">
      <div class="col-md-6">
        <h4><i class="far fa-star"></i>Simplicity Focused</h4>
        </div>
      <div class="col-md-6">
          <h4><i class="far fa-star"></i>Track Your Work Hours</h4>
        </div>
      <div class="col-md-6">
          <h4><i class="far fa-star"></i>Accurate and Efficient Workflow</h4>
      </div>
      <div class="col-md-6">
         <h4><i class="far fa-star"></i>Sustainable Time Managment</h4>
      </div>
      <div class="col-md-6">
          <h4><i class="far fa-star"></i>Manage your Projects</h4>
      </div>
      <div class="col-md-6">
          <h4><i class="far fa-star"></i>Perfect for Freelancers</h4>
      </div>
  </div>
    </div>
      </div>
          </div>
</section>

    <!-- #about -->

    <!--==========================
      Call To Action Section
    ============================-->
    <section id="call-to-action" class="wow fadeIn">
      <div class="container text-center">
        <h3 class="text-2">Having Problems keeping track on your goals?</h3>
        <p class="text-center">
         With WorkSmart you can set and track your goals, view your workflow, manage your tasks, and lots more.      </p>
        <a class="cta-btn" href="#">Get Started</a>
        <div style="margin-top: 8px;">No credit card needed &nbsp; ✦ &nbsp;  Unlimited time on Free plan</div>
      </div>
    </section><!-- #call-to-action -->

</body>
</html>