config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    # omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  root to: "pages#home"
  get "dashboard", to: "pages#dashboard"

  get "settings", to: "pages#settings"

  get "projects/completed", to: "projects#index_complete", as: "completed_projects"
  get "calendar", to: "pages#calendar", as: "calendar"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources "projects" do
    get "active", to: "projects#set_active", as: "active"
    get "unmark", to: "projects#unmark_active", as: "unmark_active"
    get "complete", to: "projects#complete", as: "complete"
    get "incomplete", to: "projects#incomplete", as: "incomplete"

    resources "tasks", only: %i[new create update destroy]
  end

  get "tasks/:id/checkbox", to: "tasks#checkbox", as: "checkbox"

  resources "schedules", only: %i[index new show create edit update destroy]
  resources "notifications", only: %i[destroy]

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :tasks, dependent: :destroy
  validates :name, :start_date, :dead_line, :hours_worked, :expected_hours, presence: true

  def start_time
    self.start_date #Where 'start' is a attribute of type 'Date' accessible through MyModel's relationship
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[show destroy]
  before_action :set_project_id, only: %i[set_active unmark_active complete incomplete]


  def show
    @tasks = @project.tasks.sort_by { |task| task[:id] }
    @completed_tasks = @project.tasks.where(completed: true)
    if @completed_tasks == []
      @percentage = 0
    else
      @percentage = ((@completed_tasks.count.to_f / @project.tasks.count) * 100).to_i
    end
  end

  def index
    @projects = current_user.projects.where(completed: false)
  end

  def index_complete
    @projects = current_user.projects.where(completed: true)
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    @project.user = current_user
    if @project.save
      redirect_to new_project_task_path(@project.id)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_path, status: :see_other
  end

  def set_active
    @projects = current_user.projects
    @projects.each do |project|
      project.update_attribute(:active, false)
    end
    @project.update_attribute(:active, true)
    @project.update_attribute(:start_count, DateTime.now)
    redirect_to dashboard_path, notice: " Project is active."
  end

  def unmark_active
    @project.update_attribute(:active, false)
    @project.update_attribute(:end_count, DateTime.now)
    hours = (((@project.end_count - @project.start_count) / 60) / 60)
    @project.hours_worked = @project.hours_worked + hours
    @project.save
    redirect_to dashboard_path, notice: " Project is unactive."
  end

  def complete
    @project.update_attribute(:completed, true)
    redirect_to completed_projects_path, notice: " Project successfully updated."
  end

  def incomplete
    @project.update_attribute(:completed, false)
    redirect_to projects_path, notice: " Project is incomplete."
  end


  private

  def set_project
    @project = Project.find(params[:id])
  end

  def set_project_id
    @project = Project.find(params[:project_id])
  end

  def project_params
    params.require(:project).permit(:name, :start_date, :dead_line, :expected_hours, :active)
  end
end

app/views/projects/_form.html.erb
  <%= simple_form_for(project) do |f| %>
      <%= f.input :name %>
      <%= f.input :start_date,
                as: :string,
                input_html: { data: { controller: "datepicker" } } %>
      <%= f.input :dead_line,
                as: :string,
                input_html: { data: { controller: "datepicker" } } %>
      <%= f.input :expected_hours,
              as: :string %>

      <%= f.submit class:"button-1 border-0 w-100 d-flex justify-content-center position5"%>

  <% end %>

app/views/projects/index.html.erb
<div class="container show-form w-75 py-3 ">
  <h1 class= "sign-text">Unfinished Projects</h1>
<br/>
  <ul>
    <% @projects.each do |project| %>
      <div class="border-project">
        <li class="d-flex w-100 justify-content-around space1">
          <p class="text-7 my-2 w-25"><%= project.name %> </p>
          <div class="p-2 align-self-center d-flex justify-content-around w-50">
            <%= link_to "View",  project_path(project.id), class:"button-5"%>
            <%= link_to "Delete",
                        project_path(project.id),
                        data: {turbo_method: :delete, turbo_confirm: "Are you sure?"},
                        class:"my-auto button-6"
            %>
          <div>
        </li>
      </div>
    <% end %>
  </ul>
  <br/>
  <%= link_to "View Completed Projects", completed_projects_path, class:"button-1 my-auto" %>
</div>

app/views/projects/index_complete.html.erb
<div class="container show-form w-75 py-3">
  <h1 class= "sign-text mb-4">All Finished Projects</h1>

  <ul>
    <% @projects.each do |project| %>
      <div class="border-project">
        <li class="d-flex w-100 justify-content-around space1">
          <p class="text-7 my-2 w-25"><%= project.name %> </p>
          <div class="p-2 align-self-center d-flex justify-content-around w-50">
            <%= link_to "View",  project_path(project.id), class:"button-5 "%>
            <%= link_to "Delete",
                        project_path(project.id),
                        data: {turbo_method: :delete, turbo_confirm: "Are you sure?"},
                        class:"my-auto button-6"
            %>
          </div>
        </li>
      </div>
    <% end %>
  </ul>
  <%= link_to "View Incomplete Projects", projects_path, class:"button-1 my-auto" %>
</div>

app/views/projects/new.html.erb
<div class="product-form">
  <div class="add-product-card">
    <h1 class="projext-field">Add a Project</h1>
    <%= render "form", project: @project %>
  </div>
</div>

app/views/projects/show.html.erb
<div class="container show-form p-3 pb-5 show-card">
  <div class="d-flex justify-content-around">

    <div class="my-3 des-proj show-card-1">
      <h1 class= "text-2 text-center"><%= @project.name %></h1>
      <div class= "li-des">
      <p class="text-start"> <i class="fa-solid fa-calendar-days"></i><b> Date Started: </b></p>
      <p class="d-flex text-align-start"><i><%= @project.start_date.strftime("%d %B %y") %></i></p>
      <p class="text-start"> <i class="fa-solid fa-hourglass-end"></i><b> Project deadline: </b></p>
      <p class="d-flex text-align-start"><i><%= @project.dead_line.strftime("%d %B %y") %></i></p>
      <p class="text-start"> <i class="fa-solid fa-clock"></i><b> Hours expected to complete this project: </b></p>
      <p class="d-flex text-align-start"><i><%= @project.expected_hours %> hours</i></p>
      <p class="text-start"> <i class="fa-solid fa-comments-dollar"></i><b> Hours spent on project: </b></p>
      <p class="d-flex text-align-start"><i><%= @project.hours_worked.round(1) %> hours</i></p>
      <p class="text-start"> <i class="fa-solid fa-square-check "></i><%= @percentage %>% completed</p>
      </div>
    </div>

    <div class="my-4 task-proj show-card-2 ">
      <h1 class= "text-2 text-11">Tasks</h1>
      <ul class="card-25">
      <% @tasks.each do |task| %>
        <% if task.completed %>
          <li class="my-3 card-27">
            <div class="card-26">
              <div class="">
                <%= link_to checkbox_path(task) do %>
                  <i class="fa-solid fa-square-check " style="color: #33ba21;"></i>
                <% end %>
              </div>
              <div class="mt-4 ">
                <%= task.name %>
              </div>
              <div class="">
                <%= link_to project_task_path(@project.id, task.id),
                            data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do
                %>
                  <i class="fa-solid fa-trash " style="color: #0dc200;"></i>
                <% end %>
              </div>
            </div>
          </li>
        <% else %>

          <li class="my-3 card-27 ">
            <div class="card-26">
              <div>
                <%= link_to checkbox_path(task) do %>
                  <i class="fa-regular fa-square" style="color: #1ae000;"></i>
                <% end %>
                <%= task.name %>
              </div>
              <div>
                <%= link_to project_task_path(@project.id, task.id),
                            data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do
                %>
                  <i class="fa-solid fa-trash" style="color: #0dc200;"></i>
                <% end %>
              </div>
            </div>
          </li>

        <% end %>
      <% end %>
      </ul>
    </div>
  </div>
  <div class="d-flex justify-content-around">
    <div>
      <% if @project.active %>
        <%= link_to "Unmark as Active", project_unmark_active_path(@project.id), class:"button-1 my-auto"%>
      <% else %>
        <%= link_to "Mark as Active", project_active_path(@project.id), class:"button-1 my-auto" %>
      <% end %>
    </div>
    <div>
      <% if @project.completed %>
        <%= link_to "Mark as Incomplete", project_incomplete_path(@project.id), class:"button-1 my-auto" %>
      <% else %>
        <%= link_to "Mark as Completed", project_complete_path(@project.id), class:"button-1 my-auto" %>
      <% end %>
    </div>
    <div>
      <%= link_to "+ Add a Task", new_project_task_path(@project.id), class:"button-1"%>
    </div>
  </div>
</div>